codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 0.5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 0.5%
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

ignore:
  - "**/*_test.go"
  - "**/vendor/**"
  - "**/examples/**"
  - "**/*.pb.go"
  - "**/mocks/**"
  - "**/testdata/**"
  - "scripts/**"
  - "docs/**"
  - "charts/**"
  - "*.md"
  - ".github/**"
  - "Dockerfile*"
  - "docker-compose.yml"
  - "Makefile"
  - "main.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: false

flags:
  unit:
    paths:
      - pkg/
    carryforward: false
  integration:
    paths:
      - pkg/
    carryforward: false